source 'https://rubygems.org'

gem 'rake'

gem 'activerecord', '>= 3.1', :require => 'active_record'
gem 'sqlite3'

gem "sinatra-resource-json-api", path: "../.."

group :test do
  gem 'rspec'
  gem 'rack-test', :require => 'rack/test'
  gem "factory_girl"
  gem "database_cleaner"
  gem "faker"
end

group :develpment, :test do
  gem "pry-byebug"
end

gem 'padrino', '0.13.0.beta2'

